BOARD_NAME = "piro-tiledb-hc-01"
BOARD_ID = "tile-hc-01"
DISCOVERY_PREFIX = "atlas.net"

WIFI_SSID = "ATLAS.NET"
WIFI_PASS = "the.atlas.net"

MQTT_BROKER = "192.168.0.200"
MQTT_PORT = 1883
MQTT_USER = "tiledb"
MQTT_PASS = "T1le-db-word!"

MQTT_BASE_TOPIC = f"{DISCOVERY_PREFIX}/{BOARD_NAME}/{BOARD_ID}"


INFLUXDB_HOST = "192.168.0.200"
INFLUXDB_PORT = 8086
INFLUXDB_USERNAME = "tiledb"
INFLUXDB_PASSWORD = "T1le-db-word!"
INFLUXDB_DATABASE = "tiledb"